#!/usr/bin/env python3
"""Generate derivation axioms + conformance fixtures from the CASED Appendix B tables.

Source: `derivation/relationships.xml` in the form kept on the `derivation-redo` branch, where the
relation letters are case-significant per the spec's own legend:

    UPPERCASE = direct relationship
    lowercase = derived relationship

Emits (all in the ontology's real term namespace, `https://purl.org/archimate#` — NOT the
`…/archimate/owl#` ontology-document IRI, which is the bug that made the previous axioms file
unable to bind to anything):

  archimate_derivation_axioms.ttl   the file to load: relationship letters, categories, the
                    permission lookup, and the permitted matrix in both forms — archi:permits<Rel>
                    (direct or derived) and archi:permitsDirect<Rel> (directly assertable).
  fixture-direct.ttl    the UPPERCASE relationships as type-level instance data — the input a
                        conformance run feeds to the ruleset.
  fixture-derived.ttl   the lowercase relationships, same shape — what the ruleset is expected to
                        reproduce. The diff of (inferred − direct) against this is the conformance
                        measurement; anything inferred but permitted nowhere is a restriction case.

Usage:  relationships2axioms.py <cased-relationships.xml> <output-dir>
"""
import sys, pathlib, xml.etree.ElementTree as ET
from collections import defaultdict

NS = "https://purl.org/archimate#"

# Letter legend from the spec (and the file's own comment).
LETTER = {
    'a': 'access',   'c': 'composition', 'f': 'flow',        'g': 'aggregation',
    'i': 'assignment', 'n': 'influence', 'o': 'association', 'r': 'realization',
    's': 'specialization', 't': 'triggering', 'v': 'serving',
}

# Weakest-link orderings, strongest -> weakest.
#   B.2.2 structural   composition > aggregation > assignment > realization
#   B.3.3 dependency   serving > access > influence > association
STRUCTURAL = ['composition', 'aggregation', 'assignment', 'realization']
DEPENDENCY = ['serving', 'access', 'influence', 'association']
DYNAMIC    = ['triggering', 'flow']
OTHER      = ['specialization']
CATEGORY   = {'Structural': STRUCTURAL, 'Dependency': DEPENDENCY,
              'Dynamic': DYNAMIC, 'Other': OTHER}


def permits_predicate(relation: str) -> str:
    return f"permits{relation[0].upper()}{relation[1:]}"


def parse(path):
    """-> direct[(src,tgt)] = {relation}, derived[(src,tgt)] = {relation}, concepts"""
    root = ET.parse(path).getroot()
    direct, derived, concepts = defaultdict(set), defaultdict(set), set()
    for s in root.findall('source'):
        sc = s.get('concept')
        if not sc:
            continue
        concepts.add(sc)
        for tg in s.findall('target'):
            tc = tg.get('concept')
            if not tc:
                continue
            concepts.add(tc)
            for ch in (tg.get('relations') or ''):
                rel = LETTER.get(ch.lower())
                if not rel:
                    continue
                (direct if ch.isupper() else derived)[(sc, tc)].add(rel)
    return direct, derived, sorted(concepts)


def closed_pairs(order):
    """Transitive closure of 'weaker than', as (weaker, stronger) pairs, plus reflexive."""
    pairs = set()
    for i, weak in enumerate(reversed(order)):          # weakest first
        rank_w = len(order) - 1 - i
        for j, strong in enumerate(order):
            if j <= rank_w:                              # strong is at least as strong
                pairs.add((weak, strong))
    return pairs


def ttl_header(title):
    return (f"# {title}\n"
            f"# GENERATED by tools/relationships2axioms.py — do not hand-edit.\n"
            f"# Source: the CASED Appendix B tables (UPPERCASE=direct, lowercase=derived).\n"
            f"@prefix archi: <{NS}> .\n"
            f"@prefix owl:   <http://www.w3.org/2002/07/owl#> .\n"
            f"@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n\n")


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, outdir = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    outdir.mkdir(parents=True, exist_ok=True)
    direct, derived, concepts = parse(src)

    # ---- permits matrix (direct ∪ derived) + permittedBy meta ----------
    permitted = defaultdict(set)
    for table in (direct, derived):
        for (s, t), rels in table.items():
            permitted[(s, t)] |= rels
    n_perm = sum(len(v) for v in permitted.values())

    # ---- conformance fixtures (type level) -----------------------------
    counts = {}
    for label, table in (("direct", direct), ("derived", derived)):
        F = [ttl_header(f"Conformance fixture — {label} relationships at type level")]
        F.append("# Concepts are treated as individuals so the relation-generic derivation rules\n"
                 "# fire over the metamodel exactly as they do over a real model.\n")
        # self-typing, so rules that dispatch on element type can still match
        if label == "direct":
            for c in concepts:
                F.append(f"archi:{c} a archi:{c} .\n")
            F.append("\n")
        n = 0
        for (s, t) in sorted(table):
            for rel in sorted(table[(s, t)]):
                F.append(f"archi:{s} archi:{rel} archi:{t} .\n")
                n += 1
        (outdir / f"fixture-{label}.ttl").write_text("".join(F))
        counts[label] = n

    # ---- consolidated replacement for archimate_derivation_axioms.ttl -----
    A = [ttl_header("ArchiMate derivation axioms — relationship strength, categories, and the "
                    "Appendix B permitted matrix")]
    A.append("# Generated from derivation/relationships.xml. Do not edit by hand.\n"
             "#\n"
             "# archi:permits<Relation>       permitted, whether directly or by derivation\n"
             "# archi:permitsDirect<Relation> permitted DIRECTLY — assertable per the metamodel\n"
             "#\n"
             "# Every permitsDirect triple is also a permits triple. A relationship that is permitted\n"
             "# but not permitted-direct is one Appendix B sanctions only as a derivation.\n\n")
    A.append("### Relationship letters (spec legend)\n")
    for ch, rel in sorted(LETTER.items()):
        A.append(f'archi:{rel} archi:relAbbreviation "{ch}" .\n')
    A.append("\n### Relationship categories\n")
    for cat, rels in CATEGORY.items():
        for rel in rels:
            A.append(f"archi:{rel} archi:relCategory archi:{cat} .\n")
    A.append("\n### Relation -> the predicate carrying its permissions\n")
    for rel in sorted(set(LETTER.values())):
        A.append(f"archi:{rel} archi:permittedBy archi:{permits_predicate(rel)} .\n")
    A.append("\n### Permitted relationships per (source, target) — direct union derived\n")
    for (s_, t_) in sorted(permitted):
        for rel in sorted(permitted[(s_, t_)]):
            A.append(f"archi:{s_} archi:{permits_predicate(rel)} archi:{t_} .\n")
    A.append("\n### Permitted DIRECTLY per (source, target) — the UPPERCASE half of the tables\n")
    n_dir = 0
    for (s_, t_) in sorted(direct):
        for rel in sorted(direct[(s_, t_)]):
            A.append(f"archi:{s_} archi:permitsDirect{rel[0].upper()}{rel[1:]} archi:{t_} .\n")
            n_dir += 1
    (outdir.parent / "archimate_derivation_axioms.ttl").write_text("".join(A))
    print(f"consolidated axioms -> {outdir.parent / 'archimate_derivation_axioms.ttl'}")

    print(f"concepts            {len(concepts)}")
    print(f"permitsDirect       {n_dir}")
    print(f"permits triples     {n_perm}")
    print(f"direct  (UPPERCASE) {counts['direct']}")
    print(f"derived (lowercase) {counts['derived']}")
    print(f"-> {outdir}")


if __name__ == "__main__":
    main()
