#!/usr/bin/env python3
"""Generate derivation axioms + conformance fixtures from the CASED Appendix B tables.

Source: `derivation/relationships.xml` in the form kept on the `derivation-redo` branch, where the
relation letters are case-significant per the spec's own legend:

    UPPERCASE = direct relationship
    lowercase = derived relationship

Emits (all in the ontology's real term namespace, `https://purl.org/archimate#` — NOT the
`…/archimate/owl#` ontology-document IRI, which is the bug that made the previous axioms file
unable to bind to anything):

  axioms-weaker.ttl     the weakest-link ordering, transitively closed, as archi:weakerOrEqual.
                        Parameterizes the derivation rules; without it the ruleset fires on nothing.
  axioms-permits.ttl    one archi:permits<Relation> triple per permitted (source, target, relation),
                        over direct ∪ derived, plus archi:permittedBy meta-triples mapping each
                        relation to its permission predicate. Used as a POSITIVE premise so
                        restriction rules need no negation.
  fixture-direct.ttl    the UPPERCASE relationships as type-level instance data — the input a
                        conformance run feeds to the ruleset.
  fixture-derived.ttl   the lowercase relationships, same shape — what the ruleset is expected to
                        reproduce. The diff of (inferred − direct) against this is the conformance
                        measurement; anything inferred but permitted nowhere is a restriction case.

Usage:  relationships2axioms.py <cased-relationships.xml> <output-dir>
"""
import sys, pathlib, xml.etree.ElementTree as ET
from collections import defaultdict

NS = "https://purl.org/archimate#"

# Letter legend from the spec (and the file's own comment).
LETTER = {
    'a': 'access',   'c': 'composition', 'f': 'flow',        'g': 'aggregation',
    'i': 'assignment', 'n': 'influence', 'o': 'association', 'r': 'realization',
    's': 'specialization', 't': 'triggering', 'v': 'serving',
}

# Weakest-link orderings, strongest -> weakest.
#   B.2.2 structural   composition > aggregation > assignment > realization
#   B.3.3 dependency   serving > access > influence > association
STRUCTURAL = ['composition', 'aggregation', 'assignment', 'realization']
DEPENDENCY = ['serving', 'access', 'influence', 'association']
DYNAMIC    = ['triggering', 'flow']
OTHER      = ['specialization']
CATEGORY   = {'Structural': STRUCTURAL, 'Dependency': DEPENDENCY,
              'Dynamic': DYNAMIC, 'Other': OTHER}


def permits_predicate(relation: str) -> str:
    return f"permits{relation[0].upper()}{relation[1:]}"


def parse(path):
    """-> direct[(src,tgt)] = {relation}, derived[(src,tgt)] = {relation}, concepts"""
    root = ET.parse(path).getroot()
    direct, derived, concepts = defaultdict(set), defaultdict(set), set()
    for s in root.findall('source'):
        sc = s.get('concept')
        if not sc:
            continue
        concepts.add(sc)
        for tg in s.findall('target'):
            tc = tg.get('concept')
            if not tc:
                continue
            concepts.add(tc)
            for ch in (tg.get('relations') or ''):
                rel = LETTER.get(ch.lower())
                if not rel:
                    continue
                (direct if ch.isupper() else derived)[(sc, tc)].add(rel)
    return direct, derived, sorted(concepts)


def closed_pairs(order):
    """Transitive closure of 'weaker than', as (weaker, stronger) pairs, plus reflexive."""
    pairs = set()
    for i, weak in enumerate(reversed(order)):          # weakest first
        rank_w = len(order) - 1 - i
        for j, strong in enumerate(order):
            if j <= rank_w:                              # strong is at least as strong
                pairs.add((weak, strong))
    return pairs


def ttl_header(title):
    return (f"# {title}\n"
            f"# GENERATED by tools/relationships2axioms.py — do not hand-edit.\n"
            f"# Source: the CASED Appendix B tables (UPPERCASE=direct, lowercase=derived).\n"
            f"@prefix archi: <{NS}> .\n"
            f"@prefix owl:   <http://www.w3.org/2002/07/owl#> .\n"
            f"@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .\n\n")


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, outdir = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    outdir.mkdir(parents=True, exist_ok=True)
    direct, derived, concepts = parse(src)

    # ---- weaker lattice -------------------------------------------------
    L = [ttl_header("Weakest-link ordering (transitively closed, reflexive)")]
    L.append("archi:weakerOrEqual a owl:ObjectProperty ;\n"
             '    rdfs:label "weaker or equal to" ;\n'
             '    rdfs:comment "Subject relation is weaker than or equal to the object relation. '
             'Transitive closure is materialized here so a ruleset need not rely on the engine '
             'expanding it." .\n\n')
    L.append("# Relationship categories, so a single rule can dispatch on category.\n")
    for cat, rels in CATEGORY.items():
        for rel in rels:
            L.append(f"archi:{rel} archi:relCategory archi:{cat} .\n")
    L.append("\n")
    n_weak = 0
    for name, order in (("B.2.2 structural", STRUCTURAL), ("B.3.3 dependency", DEPENDENCY)):
        L.append(f"# {name}: {' > '.join(order)}\n")
        for weak, strong in sorted(closed_pairs(order)):
            L.append(f"archi:{weak} archi:weakerOrEqual archi:{strong} .\n")
            n_weak += 1
        L.append("\n")
    (outdir / "axioms-weaker.ttl").write_text("".join(L))

    # ---- permits matrix (direct ∪ derived) + permittedBy meta ----------
    P = [ttl_header("Permitted relationships (direct ∪ derived) — restriction guard")]
    P.append("# archi:permittedBy maps a relation to the predicate carrying its permissions, so a\n"
             "# single generic rule can look up permission for whatever relation it is deriving.\n")
    for rel in sorted(set(LETTER.values())):
        P.append(f"archi:{rel} archi:permittedBy archi:{permits_predicate(rel)} .\n")
    P.append("\n")
    permitted = defaultdict(set)
    for table in (direct, derived):
        for (s, t), rels in table.items():
            permitted[(s, t)] |= rels
    n_perm = 0
    for (s, t) in sorted(permitted):
        for rel in sorted(permitted[(s, t)]):
            P.append(f"archi:{s} archi:{permits_predicate(rel)} archi:{t} .\n")
            n_perm += 1
    (outdir / "axioms-permits.ttl").write_text("".join(P))

    # ---- conformance fixtures (type level) -----------------------------
    counts = {}
    for label, table in (("direct", direct), ("derived", derived)):
        F = [ttl_header(f"Conformance fixture — {label} relationships at type level")]
        F.append("# Concepts are treated as individuals so the relation-generic derivation rules\n"
                 "# fire over the metamodel exactly as they do over a real model.\n")
        # self-typing, so rules that dispatch on element type can still match
        if label == "direct":
            for c in concepts:
                F.append(f"archi:{c} a archi:{c} .\n")
            F.append("\n")
        n = 0
        for (s, t) in sorted(table):
            for rel in sorted(table[(s, t)]):
                F.append(f"archi:{s} archi:{rel} archi:{t} .\n")
                n += 1
        (outdir / f"fixture-{label}.ttl").write_text("".join(F))
        counts[label] = n

    # ---- consolidated replacement for archimate_derivation_axioms.ttl -----
    A = [ttl_header("ArchiMate derivation axioms — relationship strength, categories, and the "
                    "Appendix B permitted matrix")]
    A.append("# Supersedes the previous hand-transcribed axioms file, which (a) used the ontology\n"
             "# DOCUMENT IRI <https://purl.org/archimate/owl#> as its term namespace so nothing it\n"
             "# asserted could bind to real relationships, and (b) was transcribed from an\n"
             "# all-lowercase table, discarding the spec's direct-vs-derived distinction.\n"
             "@prefix deriv: <https://purl.org/archimate/derivation#> .\n\n")
    A.append("### Relationship letters (spec legend)\n")
    for ch, rel in sorted(LETTER.items()):
        A.append(f'archi:{rel} archi:relAbbreviation "{ch}" .\n')
    A.append("\n### Relationship categories\n")
    for cat, rels in CATEGORY.items():
        for rel in rels:
            A.append(f"archi:{rel} archi:relCategory archi:{cat} .\n")
    A.append("\n### Strength ordering (B.2.2 structural, B.3.3 dependency), transitively closed\n")
    for order in (STRUCTURAL, DEPENDENCY):
        for i, strong in enumerate(order):
            for weak in order[i+1:]:
                A.append(f"archi:{weak} archi:weakerThan archi:{strong} .\n")
        for weak, strong in sorted(closed_pairs(order)):
            A.append(f"archi:{weak} archi:weakerOrEqual archi:{strong} .\n")
    A.append("\n### Permission lookup used as a positive premise by the derivation ruleset\n")
    for rel in sorted(set(LETTER.values())):
        A.append(f"archi:{rel} archi:permittedBy archi:{permits_predicate(rel)} .\n")
    A.append("\n### Permitted relationships per (source, target) — direct union derived\n")
    for (s_, t_) in sorted(permitted):
        for rel in sorted(permitted[(s_, t_)]):
            A.append(f"archi:{s_} archi:{permits_predicate(rel)} archi:{t_} .\n")
    A.append("\n### Per-pair detail, PRESERVING the spec's direct/derived split\n")
    n_ind = 0
    for (s_, t_) in sorted(set(direct) | set(derived)):
        dr = sorted(direct.get((s_, t_), ()))
        dv = sorted(derived.get((s_, t_), ()))
        A.append(f"deriv:{s_}-{t_} a deriv:ArchimateRelationshipPair ;\n"
                 f"    deriv:source archi:{s_} ;\n    deriv:target archi:{t_} ;\n")
        if dr:
            A.append("    deriv:directRelation " + ", ".join(f"archi:{r}" for r in dr) + " ;\n")
        if dv:
            A.append("    deriv:derivedRelation " + ", ".join(f"archi:{r}" for r in dv) + " ;\n")
        A.append("    .\n")
        n_ind += 1
    (outdir.parent / "archimate_derivation_axioms.ttl").write_text("".join(A))
    print(f"consolidated axioms -> {outdir.parent / 'archimate_derivation_axioms.ttl'} ({n_ind} pairs)")

    print(f"concepts            {len(concepts)}")
    print(f"weakerOrEqual pairs {n_weak}")
    print(f"permits triples     {n_perm}")
    print(f"direct  (UPPERCASE) {counts['direct']}")
    print(f"derived (lowercase) {counts['derived']}")
    print(f"-> {outdir}")


if __name__ == "__main__":
    main()
